version: "3.3"

services:
  keycloak:
    container_name: keycloak
    image: igate-ivpn.iplon.co.in:8080/keycloak/keycloak:9.0.2
    environment:
     - KEYCLOAK_USER=admin
     - KEYCLOAK_PASSWORD=password
     - DB_VENDOR=h2     
    ports:
     - "8080:8080"
    restart: always
   
  etcd:
    container_name: etcd
    image: igate-ivpn.iplon.co.in:8080/keycloak/bitnami/etcd:latest
    environment:
     - ALLOW_NONE_AUTHENTICATION=yes
     - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379     
    network_mode: "host"
    restart: always 
    
    
  apache-apisix:
    container_name: apache-apisix
    image: igate-ivpn.iplon.co.in:8080/keycloak/apache/apisix:latest
    network_mode: "host"
    restart: always
    
    
  apache-apisix-dashboard:    
    container_name: apache-apisix-dashboard
    image: igate-ivpn.iplon.co.in:8080/keycloak/apache-apisix-dashboard:latest
    network_mode: "host"
    restart: always
